# -*- coding: utf-8 -*-
"""aaa Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IiRN4gKMvMamzAkZ3gL7QM8M4YqTYxLk
"""

import streamlit as st
from datetime import date

st.title("Age Calculator")

dob = st.date_input(
    "Select DOB",
    min_value=date(1900, 1, 1),
    max_value=date.today()
)

if st.button("Calculate"):
    today = date.today()

    age = today.year - dob.year

    if (today.month, today.day) < (dob.month, dob.day):
        age -= 1

    st.success(f"Age: {age} years")