# -*- coding: utf-8 -*-
"""Advance AgeCalculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IiRN4gKMvMamzAkZ3gL7QM8M4YqTYxLk
"""

import streamlit as st
from datetime import date

# Page Config
st.set_page_config(page_title="Smart Age Calculator", page_icon="🎂")

# Title
st.title("🎂 Smart Age Calculator")
st.write("Enter your Date of Birth and calculate your exact age.")

# Custom Date Input
dob = st.date_input(
    "Select Your DOB",
    value=date(2005, 1, 1),
    min_value=date(1900, 1, 1),
    max_value=date(2100, 12, 31)
)

# Button
if st.button("Calculate Age"):

    today = date.today()

    # Age Calculation
    years = today.year - dob.year
    months = today.month - dob.month
    days = today.day - dob.day

    # Adjust negative days
    if days < 0:
        months -= 1
        days += 30

    # Adjust negative months
    if months < 0:
        years -= 1
        months += 12

    # Output
    st.success(f"🎉 Your Age is: {years} Years, {months} Months, {days} Days")

    # Extra Info
    st.info(f"📅 Selected DOB: {dob}")
    st.balloons()