# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dnV-o1oSayK0yocTBLRQWf_X1koyDWR1
"""

pip install streamlit pandas plotly requests

# ============================================================================
# ROOMMATE MATCHING APP - Complete Streamlit Website (FIXED)
# ============================================================================
# Run command: streamlit run app.py
# ============================================================================

import streamlit as st
import pandas as pd
import random
from datetime import datetime, timedelta
import hashlib
import re

# ============================================================================
# PAGE CONFIGURATION
# ============================================================================
st.set_page_config(
    page_title="RoomMate - Find Your Perfect Roommate",
    page_icon="🏠",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ============================================================================
# CUSTOM CSS
# ============================================================================
st.markdown("""
<style>
    .main-header {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        padding: 20px;
        border-radius: 15px;
        color: white;
        text-align: center;
        margin-bottom: 20px;
    }
    .feature-card {
        background: #f0f2f6;
        padding: 20px;
        border-radius: 10px;
        text-align: center;
        margin: 10px 0;
    }
    .match-card {
        background: white;
        padding: 20px;
        border-radius: 15px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        margin: 10px 0;
    }
    .score-badge {
        padding: 5px 15px;
        border-radius: 20px;
        font-weight: bold;
        display: inline-block;
    }
</style>
""", unsafe_allow_html=True)

# ============================================================================
# SESSION STATE INITIALIZATION
# ============================================================================
if 'logged_in' not in st.session_state:
    st.session_state.logged_in = False
if 'user_data' not in st.session_state:
    st.session_state.user_data = None
if 'current_page' not in st.session_state:
    st.session_state.current_page = 'home'
if 'matches' not in st.session_state:
    st.session_state.matches = []
if 'verified' not in st.session_state:
    st.session_state.verified = False
if 'otp_sent' not in st.session_state:
    st.session_state.otp_sent = False
if 'otp' not in st.session_state:
    st.session_state.otp = None

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def hash_data(data):
    """Hash sensitive data"""
    return hashlib.sha256(data.encode()).hexdigest()

def validate_email(email):
    """Validate email format"""
    pattern = r'^[\w\.-]+@[\w\.-]+\.\w+$'
    return re.match(pattern, email) is not None

def validate_phone(phone):
    """Validate Indian phone number"""
    return len(phone) == 10 and phone.isdigit() and phone[0] in '6789'

def validate_aadhaar(aadhaar):
    """Validate Aadhaar number"""
    return len(aadhaar) == 12 and aadhaar.isdigit()

def validate_age(dob):
    """Validate age (21-35)"""
    try:
        birth_date = datetime.strptime(dob, '%Y-%m-%d')
        today = datetime.now()
        age = today.year - birth_date.year - ((today.month, today.day) < (birth_date.month, birth_date.day))
        return 21 <= age <= 35, age
    except:
        return False, 0

def generate_otp():
    """Generate 6-digit OTP"""
    return str(random.randint(100000, 999999))

# ============================================================================
# SIDEBAR NAVIGATION
# ============================================================================
def sidebar():
    with st.sidebar:
        st.title("🏠 RoomMate")
        st.markdown("---")

        if st.session_state.logged_in:
            st.write(f"👤 Welcome, **{st.session_state.user_data.get('name', 'User')}**")
            st.markdown("---")

            if st.button("🏠 Home", use_container_width=True):
                st.session_state.current_page = 'home'
                st.rerun()
            if st.button("👤 My Profile", use_container_width=True):
                st.session_state.current_page = 'profile_setup'
                st.rerun()
            if st.button("🎯 Find Matches", use_container_width=True):
                st.session_state.current_page = 'matches'
                st.rerun()
            if st.button("💰 Payments", use_container_width=True):
                st.session_state.current_page = 'payments'
                st.rerun()
            if st.button("⚙️ Settings", use_container_width=True):
                st.session_state.current_page = 'settings'
                st.rerun()

            st.markdown("---")
            if st.button("🚪 Logout", use_container_width=True):
                st.session_state.logged_in = False
                st.session_state.user_data = None
                st.session_state.current_page = 'home'
                st.rerun()
        else:
            if st.button("🏠 Home", use_container_width=True):
                st.session_state.current_page = 'home'
                st.rerun()
            if st.button("📝 Register", use_container_width=True):
                st.session_state.current_page = 'register'
                st.rerun()
            if st.button("🔐 Login", use_container_width=True):
                st.session_state.current_page = 'login'
                st.rerun()

# ============================================================================
# HOME PAGE
# ============================================================================
def home_page():
    # Hero Section
    st.markdown("""
    <div class="main-header">
        <h1>🏠 RoomMate</h1>
        <h3>Find Your Perfect Roommate Safely</h3>
    </div>
    """, unsafe_allow_html=True)

    col1, col2 = st.columns([1, 1])

    with col1:
        st.markdown("""
        ### ✨ Features:
        - 🔐 **Aadhaar Verified Users**
        - 🎯 **Smart AI Matching**
        - 💰 **Secure Payments (30% commission)**
        - 🛡️ **Privacy First**

        ### 📊 Stats:
        - ✅ 10,000+ Verified Users
        - ✅ 5,000+ Successful Matches
        - ✅ 95% Satisfaction Rate
        """)

        if not st.session_state.logged_in:
            if st.button("🚀 Get Started - Free", type="primary", use_container_width=True):
                st.session_state.current_page = 'register'
                st.rerun()

    with col2:
        st.markdown("""
        ### 🎯 How It Works:

        **Step 1:** 📝 Register with email & phone

        **Step 2:** 🔐 Verify Aadhaar via OTP

        **Step 3:** 👤 Complete your profile

        **Step 4:** 📍 Set location & budget

        **Step 5:** 🎯 Get matched with compatible roommates

        **Step 6:** 💰 Pay rent → Contact revealed
        """)

    # Features Cards
    st.markdown("---")
    st.title("🌟 Why Choose RoomMate?")

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.markdown("""
        <div class="feature-card">
            <h2>🔐</h2>
            <h4>Verified</h4>
            <p>All users verified via Aadhaar</p>
        </div>
        """, unsafe_allow_html=True)

    with col2:
        st.markdown("""
        <div class="feature-card">
            <h2>🎯</h2>
            <h4>Smart Match</h4>
            <p>AI-powered compatibility</p>
        </div>
        """, unsafe_allow_html=True)

    with col3:
        st.markdown("""
        <div class="feature-card">
            <h2>🛡️</h2>
            <h4>Privacy</h4>
            <p>Contact hidden until payment</p>
        </div>
        """, unsafe_allow_html=True)

    with col4:
        st.markdown("""
        <div class="feature-card">
            <h2>💰</h2>
            <h4>Secure Pay</h4>
            <p>Razorpay protected</p>
        </div>
        """, unsafe_allow_html=True)

    # Testimonials
    st.markdown("---")
    st.title("💬 What Users Say")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.info("""
        **"Found my perfect roommate in 2 days!"**

        - Priya S., Mumbai

        ⭐⭐⭐⭐⭐
        """)

    with col2:
        st.info("""
        **"Very safe and verified platform"**

        - Rahul K., Bangalore

        ⭐⭐⭐⭐⭐
        """)

    with col3:
        st.info("""
        **"Payment process was smooth"**

        - Sneha M., Delhi

        ⭐⭐⭐⭐⭐
        """)

# ============================================================================
# REGISTER PAGE
# ============================================================================
def register_page():
    st.title("📝 Create Account")
    st.subheader("Join 10,000+ verified users")

    with st.form("register_form"):
        col1, col2 = st.columns(2)

        with col1:
            name = st.text_input("Full Name *")
            email = st.text_input("Email *")
            phone = st.text_input("Phone Number *", max_chars=10)
            gender = st.selectbox("Gender *", ["Select", "Male", "Female"])

        with col2:
            dob = st.date_input(
                "Date of Birth *",
                min_value=datetime.now() - timedelta(days=35*365),
                max_value=datetime.now() - timedelta(days=21*365)
            )
            password = st.text_input("Password *", type="password")
            confirm_password = st.text_input("Confirm Password *", type="password")
            looking_for = st.selectbox("Looking For", ["Any", "Male", "Female"])

        submitted = st.form_submit_button("🚀 Create Account", type="primary", use_container_width=True)

        if submitted:
            errors = []

            if len(name) < 2:
                errors.append("Name must be at least 2 characters")

            if not validate_email(email):
                errors.append("Invalid email format")

            if not validate_phone(phone):
                errors.append("Phone must be 10 digits (starting with 6-9)")

            if gender == "Select":
                errors.append("Please select gender")

            age_valid, age = validate_age(dob.strftime('%Y-%m-%d'))
            if not age_valid:
                errors.append(f"Age must be 21-35 (your age: {age})")

            if len(password) < 8:
                errors.append("Password must be at least 8 characters")

            if password != confirm_password:
                errors.append("Passwords do not match")

            if errors:
                for error in errors:
                    st.error(f"❌ {error}")
            else:
                st.session_state.user_data = {
                    'name': name,
                    'email': email,
                    'phone': phone,
                    'gender': gender.lower(),
                    'dob': dob.strftime('%Y-%m-%d'),
                    'age': age,
                    'looking_for': looking_for.lower(),
                    'verified': False
                }
                st.session_state.logged_in = True
                st.success("✅ Registration successful! Please verify Aadhaar.")
                st.session_state.current_page = 'verify_aadhaar'
                st.rerun()

# ============================================================================
# LOGIN PAGE
# ============================================================================
def login_page():
    st.title("🔐 Login")
    st.subheader("Welcome back!")

    with st.form("login_form"):
        email = st.text_input("Email")
        password = st.text_input("Password", type="password")
        submitted = st.form_submit_button("🔐 Login", type="primary", use_container_width=True)

        if submitted:
            if email and password:
                st.session_state.logged_in = True
                st.session_state.user_data = {
                    'name': 'Demo User',
                    'email': email,
                    'verified': True
                }
                st.success("✅ Login successful!")
                st.session_state.current_page = 'home'
                st.rerun()
            else:
                st.error("❌ Please enter email and password")

# ============================================================================
# AADHAAR VERIFICATION PAGE
# ============================================================================
def verify_aadhaar_page():
    st.title("🔐 Aadhaar Verification")
    st.subheader("Required for safety and trust")

    st.info("⚠️ Your Aadhaar number is encrypted and never stored in raw form.")

    if not st.session_state.otp_sent:
        with st.form("aadhaar_form"):
            aadhaar = st.text_input("Aadhaar Number (12 digits) *", max_chars=12)
            send_otp = st.form_submit_button("📱 Send OTP", type="primary", use_container_width=True)

            if send_otp:
                if validate_aadhaar(aadhaar):
                    st.session_state.otp = generate_otp()
                    st.session_state.otp_sent = True
                    st.rerun()
                else:
                    st.error("❌ Please enter valid 12-digit Aadhaar number")
    else:
        st.success(f"✅ OTP sent! (Demo OTP: **{st.session_state.otp}**)")

        with st.form("otp_form"):
            otp_input = st.text_input("Enter 6-digit OTP *", max_chars=6)

            col1, col2 = st.columns(2)
            with col1:
                verify_otp = st.form_submit_button("✅ Verify OTP", type="primary", use_container_width=True)
            with col2:
                resend = st.form_submit_button("🔄 Resend OTP", use_container_width=True)

            if verify_otp:
                if otp_input == st.session_state.otp:
                    st.session_state.verified = True
                    st.session_state.user_data['verified'] = True
                    st.success("✅ Aadhaar verified successfully!")
                    st.session_state.current_page = 'profile_setup'
                    st.rerun()
                else:
                    st.error("❌ Invalid OTP. Please try again.")

            if resend:
                st.session_state.otp = generate_otp()
                st.rerun()

# ============================================================================
# PROFILE SETUP PAGE
# ============================================================================
def profile_setup_page():
    st.title("👤 Complete Your Profile")
    st.subheader("Help us find your perfect roommate")

    with st.form("profile_form"):
        col1, col2 = st.columns(2)

        with col1:
            bio = st.text_area("Bio / About Me *", height=100)
            occupation = st.text_input("Occupation")
            company = st.text_input("Company / College")
            income = st.selectbox("Monthly Income",
                                ["Select", "< 25K", "25K-50K", "50K-1L", "> 1L"])

        with col2:
            food_pref = st.selectbox("Food Preference", ["Veg", "Non-Veg", "Both"])
            smoking = st.checkbox("Smoking")
            drinking = st.checkbox("Drinking")
            pets = st.checkbox("Open to Pets")
            sharing = st.selectbox("Accommodation Type",
                                 ["1BHK", "2BHK", "3BHK", "Hostel", "PG"])

        submitted = st.form_submit_button("💾 Save Profile", type="primary", use_container_width=True)

        if submitted:
            if bio:
                if st.session_state.user_data is None:
                    st.session_state.user_data = {}

                st.session_state.user_data.update({
                    'bio': bio,
                    'occupation': occupation,
                    'company': company,
                    'income': income,
                    'food_pref': food_pref.lower(),
                    'smoking': smoking,
                    'drinking': drinking,
                    'pets': pets,
                    'sharing': sharing
                })
                st.success("✅ Profile saved!")
                st.session_state.current_page = 'preferences'
                st.rerun()
            else:
                st.error("❌ Please fill bio")

# ============================================================================
# PREFERENCES PAGE
# ============================================================================
def preferences_page():
    st.title("📍 Location & Budget")
    st.subheader("Set your preferences for matching")

    with st.form("preferences_form"):
        col1, col2 = st.columns(2)

        with col1:
            city = st.text_input("City *")
            area = st.text_input("Area / Neighborhood *")
            state = st.selectbox("State",
                               ["Select", "Maharashtra", "Karnataka", "Delhi",
                                "Tamil Nadu", "Telangana", "Gujarat", "Uttar Pradesh"])
            pincode = st.text_input("Pincode *", max_chars=6)

        with col2:
            min_budget = st.number_input("Min Budget (₹)", min_value=3000, value=5000, step=1000)
            max_budget = st.number_input("Max Budget (₹)", min_value=5000, value=20000, step=1000)
            looking_for = st.selectbox("Looking For", ["Any", "Male", "Female"])

        submitted = st.form_submit_button("🎯 Find Matches", type="primary", use_container_width=True)

        if submitted:
            if city and area and state != "Select" and pincode:
                if st.session_state.user_data is None:
                    st.session_state.user_data = {}

                st.session_state.user_data.update({
                    'city': city,
                    'area': area,
                    'state': state,
                    'pincode': pincode,
                    'min_budget': min_budget,
                    'max_budget': max_budget,
                    'looking_for': looking_for.lower()
                })
                st.success("✅ Preferences saved!")
                st.session_state.current_page = 'matches'
                st.rerun()
            else:
                st.error("❌ Please fill all location fields")

# ============================================================================
# MATCHES PAGE
# ============================================================================
def matches_page():
    st.title("🎯 Potential Matches")
    st.subheader("Found compatible roommates near you")

    if not st.session_state.matches:
        st.session_state.matches = [
            {
                'id': 1,
                'name': 'Priya Sharma',
                'age': 24,
                'gender': 'female',
                'city': 'Mumbai',
                'budget': '₹8K-₹15K',
                'food': 'Veg',
                'sharing': '2BHK',
                'bio': 'Clean and quiet person who loves cooking and reading.',
                'score': 85
            },
            {
                'id': 2,
                'name': 'Rahul Verma',
                'age': 26,
                'gender': 'male',
                'city': 'Mumbai',
                'budget': '₹10K-₹18K',
                'food': 'Both',
                'sharing': '1BHK',
                'bio': 'Software engineer, love to travel and explore new places.',
                'score': 75
            },
            {
                'id': 3,
                'name': 'Sneha Patel',
                'age': 23,
                'gender': 'female',
                'city': 'Mumbai',
                'budget': '₹7K-₹12K',
                'food': 'Veg',
                'sharing': 'PG',
                'bio': 'Student, looking for peaceful place to study.',
                'score': 70
            },
            {
                'id': 4,
                'name': 'Amit Kumar',
                'age': 28,
                'gender': 'male',
                'city': 'Mumbai',
                'budget': '₹12K-₹20K',
                'food': 'Non-Veg',
                'sharing': '2BHK',
                'bio': 'Working professional, fitness enthusiast.',
                'score': 65
            }
        ]

    if st.session_state.matches:
        st.write(f"**{len(st.session_state.matches)} matches found**")
        st.markdown("---")

        for match in st.session_state.matches:
            with st.container():
                col1, col2, col3 = st.columns([1, 3, 1])

                with col1:
                    st.markdown(f"""
                    <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                                padding: 30px; border-radius: 15px; text-align: center; color: white;">
                        <h1 style="margin: 0; font-size: 48px;">{match['name'][0]}</h1>
                    </div>
                    """, unsafe_allow_html=True)

                with col2:
                    st.markdown(f"### {match['name']}")

                    gender_emoji = "👦" if match['gender'] == 'male' else "👧"
                    st.write(f"Age {match['age']} • {gender_emoji} {match['gender'].title()} • 📍 {match['city']}")
                    st.write(f"💰 Budget: {match['budget']} | 🏠 {match['sharing']}")
                    st.write(f"🍽️ Food: {match['food']}")
                    st.write(f"💬 *\"{match['bio']}\"*")

                    # Score badge
                    if match['score'] >= 80:
                        score_color = "#10B981"
                        score_label = "⭐ Excellent Match"
                    elif match['score'] >= 60:
                        score_color = "#F59E0B"
                        score_label = "👍 Good Match"
                    else:
                        score_color = "#EF4444"
                        score_label = "🤔 Decent Match"

                    st.markdown(f"""
                    <span class="score-badge" style="background-color: {score_color}; color: white;">
                        {match['score']}% - {score_label}
                    </span>
                    """, unsafe_allow_html=True)

                with col3:
                    st.write("")
                    st.write("")
                    if st.button("❤️ Like", key=f"like_{match['id']}", use_container_width=True):
                        st.success(f"✅ Interest sent to {match['name']}!")
                    if st.button("❌ Pass", key=f"reject_{match['id']}", use_container_width=True):
                        st.session_state.matches.remove(match)
                        st.rerun()

                st.markdown("---")
    else:
        st.info("🔍 No more matches. Check back later!")
        if st.button("🔄 Refresh Matches"):
            st.session_state.matches = []
            st.rerun()

# ============================================================================
# PAYMENTS PAGE
# ============================================================================
def payments_page():
    st.title("💰 Payments")
    st.subheader("Secure payment to finalize arrangement")

    st.warning("🔒 Contact details revealed ONLY after payment")

    col1, col2 = st.columns(2)

    with col1:
        st.markdown("### 📊 Payment Breakdown:")

        rent = st.number_input("Rent Amount (₹)", min_value=1000, value=10000, step=500)
        commission = int(rent * 0.30)
        partner_amount = rent - commission

        st.markdown(f"""
        | Item | Amount |
        |------|--------|
        | **Rent Amount** | ₹{rent:,} |
        | **App Commission (30%)** | ₹{commission:,} |
        | **To Partner (70%)** | ₹{partner_amount:,} |
        | **Total** | **₹{rent:,}** |
        """)

    with col2:
        st.markdown("""
        ### 🛡️ Security Features:

        - ✅ **Razorpay Secured**
        - ✅ **PCI-DSS Compliant**
        - ✅ **End-to-End Encrypted**
        - ✅ **Contact Hidden Until Payment**
        - ✅ **Refund Protection**
        - ✅ **24/7 Support**
        """)

    st.markdown("---")

    if st.button(f"💳 Pay ₹{rent:,}", type="primary", use_container_width=True):
        st.success("🎉 Payment successful! Contact details revealed below.")

        st.markdown("---")
        st.markdown("### 📞 Partner Contact Details:")

        col1, col2 = st.columns(2)
        with col1:
            st.markdown("""
            **Name:** Priya Sharma

            **Phone:** +91 98XXX XXX45

            **Email:** priya.XXX@email.com
            """)

        with col2:
            st.markdown("""
            **Location:** Andheri West, Mumbai

            **Pincode:** 400053

            **Apartment:** B-403, Galaxy Heights
            """)

        st.info("💬 You can now chat directly with your roommate!")

# ============================================================================
# SETTINGS PAGE
# ============================================================================
def settings_page():
    st.title("⚙️ Settings")
    st.subheader("Manage your account")

    col1, col2 = st.columns(2)

    with col1:
        st.markdown("### 👤 Account:")
        if st.button("Edit Profile", use_container_width=True):
            st.session_state.current_page = 'profile_setup'
            st.rerun()
        if st.button("Change Password", use_container_width=True):
            st.info("Password change feature coming soon")
        if st.button("Privacy Settings", use_container_width=True):
            st.info("Privacy settings coming soon")
        if st.button("Notification Settings", use_container_width=True):
            st.info("Notification settings coming soon")

    with col2:
        st.markdown("### 🆘 Support:")
        if st.button("Help Center", use_container_width=True):
            st.info("Help center coming soon")
        if st.button("Report Issue", use_container_width=True):
            st.info("Report issue feature coming soon")
        if st.button("Terms & Conditions", use_container_width=True):
            st.info("Terms & Conditions")
        if st.button("Privacy Policy", use_container_width=True):
            st.info("Privacy Policy")

    st.markdown("---")

    if st.button("🚪 Logout", type="secondary", use_container_width=True):
        st.session_state.logged_in = False
        st.session_state.user_data = None
        st.session_state.current_page = 'home'
        st.session_state.otp_sent = False
        st.rerun()

# ============================================================================
# MAIN APP
# ============================================================================
def main():
    sidebar()

    page = st.session_state.current_page

    if page == 'home':
        home_page()
    elif page == 'register':
        register_page()
    elif page == 'login':
        login_page()
    elif page == 'verify_aadhaar':
        verify_aadhaar_page()
    elif page == 'profile_setup':
        profile_setup_page()
    elif page == 'preferences':
        preferences_page()
    elif page == 'matches':
        matches_page()
    elif page == 'payments':
        payments_page()
    elif page == 'settings':
        settings_page()

if __name__ == "__main__":
    main()

