# -*- coding: utf-8 -*-
"""currency calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qK9KR5NI7w7_gsi9cyh9RpQ1fbJ91i4_
"""

# Import Streamlit library
import streamlit as st


# Create app title
st.title("Currency Converter")


# Input amount from user
amount = st.number_input(
    "Enter Amount",
    min_value=0.0
)


# Dropdown to select source currency
from_currency = st.selectbox(
    "From",
    ["INR", "USD", "EUR"]
)


# Dropdown to select target currency
to_currency = st.selectbox(
    "To",
    ["INR", "USD", "EUR"]
)


# Sample conversion rates
rates = {
    ("INR","USD"):0.012,
    ("USD","INR"):83,
    ("INR","EUR"):0.011,
    ("EUR","INR"):90,
    ("USD","EUR"):0.92,
    ("EUR","USD"):1.08
}


# Convert button
if st.button("Convert"):


    # If both currencies same
    if from_currency == to_currency:
        result = amount


    # Otherwise use conversion rate
    else:
        result = amount * rates[(from_currency,to_currency)]


    # Show result
    st.success(
        f"{amount} {from_currency} = {result:.2f} {to_currency}"
    )