# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-SKicRoaBDftO1lPfCcscNDHDdZBORR6

Q2. Create a Streamlit application that allows users to enter student details and view the information on the screen.
Requirements
Display a title and a short description of the application.
Accept student name using a text box.
Accept roll number using a number input field.
Accept course selection using a dropdown menu.
Accept subjects using a multi-select option.
Accept marks using a slider.
Add a button to display the entered information.
Show a success message after submission.
Display all entered details in a well-formatted manner.
Expected Features:
User-friendly interface
Proper labels for all input fields
Clear presentation of submitted data
"""

import streamlit as st

st.set_page_config(
    page_title="Student Details Form",
    page_icon="🎓",
    layout="centered"
)

st.title("🎓 Student Details Entry Form")
st.markdown("""
Welcome to the **Student Information Portal**.
""")
st.divider()

st.subheader("📝 Enter Student Details")
 # 1. Student Name
name = st.text_input(
    label="Student Name",
    placeholder="e.g. Rahul Sharma",
    help="Enter the full name of the student"
)

# 2. Roll Number
roll_number = st.number_input(
    label="Roll Number",
    min_value=1,
    max_value=9999,
    step=1,
    help="Enter a roll number between 1 and 9999"
)

# 3. Course Selection (Dropdown)
course = st.selectbox(
    label="Select Course",
    options=[
        "-- Select a Course --",
        "B.Tech Computer Science",
        "B.Tech Information Technology",
        "BCA",
        "MCA",
        "B.Sc Data Science",
        "MBA",
        "B.Com",
        "B.Sc Mathematics"
    ],
    help="Choose the course the student is enrolled in"
)

# 4. Subjects (Multi-select)
subjects = st.multiselect(
    label="Select Subjects",
    options=[
        "Mathematics",
        "Physics",
        "Chemistry",
        "Computer Science",
        "Data Structures",
        "Machine Learning",
        "Python Programming",
        "Database Management",
        "Operating Systems",
        "Web Development",
        "English",
        "Statistics"
    ],
    default=["Mathematics", "English"],
    help="Select one or more subjects"
)

# 5. Marks (Slider)
marks = st.slider(
    label="Marks Obtained (out of 100)",
    min_value=0,
    max_value=100,
    value=75,
    step=1,
    help="Drag the slider to set the marks obtained"
)

# Live grade indicator
if marks >= 90:
    grade = "A+ "
    grade_color = "green"
elif marks >= 75:
    grade = "A "
    grade_color = "green"
elif marks >= 60:
    grade = "B "
    grade_color = "blue"
elif marks >= 45:
    grade = "C "
    grade_color = "orange"
else:
    grade = "F "
    grade_color = "red"

st.markdown(f"**Grade Preview:** :{grade_color}[{grade}]")

st.divider()

submit = st.button("Submit Details", use_container_width=True, type="primary")

if submit:
    # Validation
    errors = []
    if not name.strip():
        errors.append("❗ Student Name cannot be empty.")
    if course == "-- Select a Course --":
        errors.append("❗ Please select a valid Course.")
    if not subjects:
        errors.append("❗ Please select at least one Subject.")

    if errors:
        for error in errors:
            st.error(error)
    else:
        # Success message
        st.success(" Student details submitted successfully!")
        st.balloons()

        st.divider()
        st.subheader("Submitted Student Information")

        # Display card using columns
        col1, col2 = st.columns(2)

        with col1:
            st.markdown(" **Student Name**")
            st.info(name.strip().title())

            st.markdown("**Course Enrolled**")
            st.info(course)

            st.markdown(" **Marks Obtained**")
            st.info(f"{marks} / 100")

        with col2:
            st.markdown("**Roll Number**")
            st.info(int(roll_number))

            st.markdown(" **Grade**")
            st.info(grade)

            st.markdown("*Total Subjects Selected**")
            st.info(len(subjects))

        # Subjects list
        st.markdown("**Subjects Selected**")
        subject_cols = st.columns(3)
        for i, subject in enumerate(subjects):
            with subject_cols[i % 3]:
                st.success(f"✔ {subject}")

        st.divider()

        # Progress bar for marks
        st.markdown("**Performance Indicator**")
        st.progress(marks / 100)
        st.caption(f"Score: {marks}%  |  Grade: {grade}")

        # Summary table
        st.divider()
        st.subheader("Summary Table")
        summary_data = {
            "Field": ["Name", "Roll Number", "Course", "Subjects Count", "Marks", "Grade"],
            "Details": [
                name.strip().title(),
                str(int(roll_number)),
                course,
                str(len(subjects)),
                f"{marks}/100",
                grade
            ]
        }
        st.table(summary_data)
